name: Update the Quote

on:
  workflow_dispatch:

jobs:
  update-the-quote:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::reticulate
            any::rmarkdown

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Update the quote
        run: |
          Rscript -e 'reticulate::py_install("requests")'
          Rscript -e 'rmarkdown::render("README.Rmd")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Update README.md"
          git push
